name: Run tests

on: [push, pull_request]

jobs:
    test:
        services:
            image: mariadb
            ports:
                - 3306
            env:
                MYSQL_ROOT_PASSWORD: root
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/cache@v1
              id: cache-composer
              with:
                  path: ~/.composer/cache
                  key: ${{ runner.os }}-composer

            - uses: actions/cache@v1
              id: cache-wp-cli
              with:
                  path: ~/.wp-cli/cache
                  key: ${{ runner.os }}-wp-cli

            - name: Run tests
              run: .github/run-tests
