name: Run tests

on:
    push:
        paths:
            - "**.php"
            - "**.json"
            - tools/test-github
    pull_request:
        paths:
            - "**.php"
            - "**.json"
            - tools/test-github

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run tests
              run: |
                  tools/test-github
